# Generated by Django 3.2.2 on 2022-06-12 02:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', cloudinary.models.CloudinaryField(default='default.png', max_length=255, null=True, verbose_name='image')),
                ('bio', models.TextField(blank=True, default='My Bio', max_length=500)),
                ('contact', models.EmailField(blank=True, max_length=100)),
            ],
        ),
    ]
